### ISSUE TITLE
Error 404 - Saving Settings

### ISSUE THREAD

**Issue by jay448** [sblantipodi/smart_watch_winder#1]
Hi there,

I was just trying to get this project working based on firmware uploaded. Strange thing is that when I fill in all the fiels except for additional param (because I'm not sure what to fill in here) the next webpage gives me a 404 and the settings I filled in did not apply.

Am I doing something wrong? What should be filled in on this field?

**Additional Param Field**
![image](https://user-images.githubusercontent.com/1663401/103479632-54ba5a00-4dcf-11eb-8c11-c0742fd53188.png)

**Error Page**
![image](https://user-images.githubusercontent.com/1663401/103479633-57b54a80-4dcf-11eb-88b2-72dbcd2e3fbb.png)

**Comment by sblantipodi** [comment]
@jay448 please reflash your ESP device and enter a 0 in that "additional param" field.
once you click store config the ESP reboot and the access point is disabled.

if you have correctly entered all the other params for WiFi and MQTT your ESP will be connected to the network and could be used to be a watchwinder 😃 

if you have flashed the "WatchWinder_1_ESP8266_firmware.bin"
you can start and stop the watchwinder using these topics:

```
    command_topic: "cmnd/watchwinder_1/POWER"
    state_topic: "stat/watchwinder_1/POWER"
```

Hope it helped.

**Comment by jay448** [comment]
That did the trick! 

Thanks so much! Now it's time to figure out how to make a nice enclosure :)

**Comment by sblantipodi** [comment]
@jay448 thanks for the feedback.
if you like the project don't forget to cast a star here on GitHub.

and please, send me some photos of your enclosure if you'll ever build it 😄 

closing the issue, feel free to open a new one if you need it 😃
