### ISSUE TITLE
Question: Mounting hardware

### ISSUE THREAD

**Issue by jay448** [sblantipodi/smart_watch_winder#3]
Hi again,

I've been messing around trying to mount the motor to a piece of wood and to the watch case I got. However, I've been trying to find how you did it. Could you perhaps share the name of the following item you used? 

![Screenshot 2021-01-20 102126](https://user-images.githubusercontent.com/1663401/105154944-5774b900-5b0a-11eb-9bb2-5c6e53f9d3e1.png)

Thanks!

**Comment by sblantipodi** [comment]
@jay448 
try to search for flange coupling 5mm on amazon 😃 

closing the issue, feel free to reply to this issue if you have other questions.

thanks.
