### ISSUE TITLE
Lovelace Dashboard

### ISSUE THREAD

**Issue by jay448** [sblantipodi/smart_watch_winder#4]
Hi! I've kept this project on a pause for a few months but I've just picked it up again.
Would you mind sharing your lovelace dashboard / card. I love the way it looks and it would make my life a littlebit easier.

Thanks!

**Comment by sblantipodi** [comment]
I'm sorry for the late reply, I haven't seen this issue before.

**Comment by sblantipodi** [comment]
> Hi! I've kept this project on a pause for a few months but I've just picked it up again.
> Would you mind sharing your lovelace dashboard / card. I love the way it looks and it would make my life a littlebit easier.
> 
> Thanks! 

Home Assistant package is available here:
https://github.com/sblantipodi/smart_watch_winder/blob/master/home_assistant_watchwinder_package.yaml
