### ISSUE TITLE
Beginner Issues loading project onto Arduino

### ISSUE THREAD

**Issue by mw2327** [sblantipodi/smart_watch_winder#5]
I'll start by saying this is my first attempt to do a project with either raspi or Arduino, but I found this watch winder project to be really interesting and I really wanted to try building it.

I have all of the components you listed and was able to successfully configure Home Assistant on the raspberry pi 4.

I have not had luck installing the watch winder project onto the ESP8266EX D1 Mini. I have access to both Arduino IDE and ESPHome, but I do not fully understand the process to make sure the Arduino has the correct components installed.

If there is any help you or others can provide, I would appreciate it.

**Comment by sblantipodi** [comment]
Hi @mw2327, thank you for your interest in the project.
This project in particular uses PlatformIO, it will be easyer for you to start with PlatformIO over Arduino IDE.

This is not really the right place where to start it all but I recommend using the PlatformIO community to learn how to use it, how to program ESP8266 and how to create your first project.
Once done first steps, this project will be easyer :)

I'll leave the issue opened if someone else wants to chime in...

**Comment by mw2327** [comment]
Thanks,

Using PlatformIO, I believe I have everything build on the ESP8266. Now I need to figure out how to configure the screen and recognize the device/entity on Home Assistant

**Comment by sblantipodi** [comment]
screen should not be configured, it should be "connected to the ESP".
if you successfully connected the screen to the ESP it should work :)

**Comment by mw2327** [comment]
> screen should not be configured, it should be "connected to the ESP".
> if you successfully connected the screen to the ESP it should work :)

sorry, I meant on the Home Assistant App, it doesn't seem to recognize the ESP when I plug it in after build/upload
